[package]
name = "neuron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ["simd_support"] }
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
opencl3 = "0.9.2"